# This is a basic workflow to help you get started with Actions

name: Deploy Script

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: "Deploy to Server"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    steps:

      - name: Git Pull
        uses: docker://evaneos/ssh-action:0.1.0
        with:
          hosts:  ${{ secrets.PROD_SSH_HOST }}
          user: ${{ secrets.PROD_SSH_USER }}
          private_key: ${{ secrets.PROD_SSH_KEY }}
          commands: git -C ${{ secrets.SITE_REPO_FOLDER }} pull origin

      - name: Install Requirements File
        uses: docker://evaneos/ssh-action:0.1.0
        with:
          hosts: ${{ secrets.PROD_SSH_HOST }}
          user: ${{ secrets.PROD_SSH_USER }}
          private_key: ${{ secrets.PROD_SSH_KEY }}
          commands: sudo ${{ secrets.SITE_PYTHON_ENV }}/env/bin/pip3 install -r ${{ secrets.SITE_REPO_FOLDER }}/requirements.txt

      - name: Collect Static Files
        uses: docker://evaneos/ssh-action:0.1.0
        with:
          hosts:  ${{ secrets.PROD_SSH_HOST }}
          user: ${{ secrets.PROD_SSH_USER }}
          private_key: ${{ secrets.PROD_SSH_KEY }}
          commands: sudo ${{ secrets.SITE_PYTHON_ENV }}/env/bin/python ${{ secrets.SITE_REPO_FOLDER }}/manage.py collectstatic --noinput

      - name: Collect Run Database Migration
        uses: docker://evaneos/ssh-action:0.1.0
        with:
          hosts:  ${{ secrets.PROD_SSH_HOST }}
          user: ${{ secrets.PROD_SSH_USER }}
          private_key: ${{ secrets.PROD_SSH_KEY }}
          commands: sudo ${{ secrets.SITE_PYTHON_ENV }}/env/bin/python ${{ secrets.SITE_REPO_FOLDER }}/manage.py migrate --noinput

      - name: Restart Gunicorn
        uses: docker://evaneos/ssh-action:0.1.0
        with:
          hosts:  ${{ secrets.PROD_SSH_HOST }}
          user: ${{ secrets.PROD_SSH_USER }}
          private_key: ${{ secrets.PROD_SSH_KEY }}
          commands: sudo systemctl restart gunicorn

      - name: Restart Nginx
        uses: docker://evaneos/ssh-action:0.1.0
        with:
          hosts:  ${{ secrets.PROD_SSH_HOST }}
          user: ${{ secrets.PROD_SSH_USER }}
          private_key: ${{ secrets.PROD_SSH_KEY }}
          commands: sudo systemctl restart nginx
