# Generated by Django 3.1 on 2020-08-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioCastellano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_text', models.TextField()),
                ('bio_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BioIngles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_text', models.TextField()),
                ('bio_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=70)),
                ('subhead', models.TextField()),
                ('blog_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_portrait', models.ImageField(upload_to='')),
                ('twitter_url', models.CharField(max_length=40)),
                ('linked_in_url', models.CharField(max_length=40)),
                ('facebook_url', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_image', models.ImageField(upload_to='')),
                ('portfolio_dscription', models.TextField()),
                ('portfolio_item_hosting', models.CharField(choices=[('PD', 'PDF'), ('EX', 'ExternalSite')], default='PD', max_length=2)),
                ('bio_file', models.FileField(upload_to='')),
            ],
        ),
    ]
