# Generated by Django 3.1 on 2020-08-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioCastellano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_text', models.TextField()),
                ('bio_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Bio Castellano',
                'verbose_name_plural': 'Bio Castellano',
            },
        ),
        migrations.CreateModel(
            name='BioIngles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_text', models.TextField()),
                ('bio_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Bio Inglés',
                'verbose_name_plural': 'Bio Inglés',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=70)),
                ('subhead', models.TextField()),
                ('fecha_de_publicacion', models.DateTimeField(auto_now_add=True)),
                ('blog_image', models.ImageField(upload_to='')),
                ('blog_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Datos de Contacto',
                'verbose_name_plural': 'Datos de Contacto',
            },
        ),
        migrations.CreateModel(
            name='HomePageItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_portrait', models.ImageField(upload_to='')),
                ('twitter_url', models.CharField(max_length=40)),
                ('linked_in_url', models.CharField(max_length=40)),
                ('youtube_url', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_image', models.ImageField(upload_to='')),
                ('portfolio_description', models.TextField()),
                ('portfolio_item_hosting', models.CharField(choices=[('EX', 'ExternalSite'), ('PD', 'PDF')], default='PD', max_length=2)),
                ('bio_file', models.FileField(blank=True, upload_to='')),
                ('external_site_url', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
    ]
