# Generated by Django 3.1 on 2020-09-11 00:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioCastellano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_text', ckeditor.fields.RichTextField()),
                ('bio_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Bio Castellano',
                'verbose_name_plural': 'Bio Castellano',
            },
        ),
        migrations.CreateModel(
            name='BioIngles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_text', ckeditor.fields.RichTextField()),
                ('bio_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Bio Inglés',
                'verbose_name_plural': 'Bio Inglés',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=70)),
                ('subhead', models.TextField()),
                ('fecha_de_publicacion', models.DateTimeField(auto_now_add=True)),
                ('blog_image', models.ImageField(upload_to='')),
                ('blog_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('twitter_url', models.CharField(max_length=40)),
                ('linked_in_url', models.CharField(max_length=40)),
                ('youtube_url', models.CharField(max_length=40)),
                ('instagram_url', models.CharField(max_length=40)),
                ('telegram_url', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Datos de Contacto',
                'verbose_name_plural': 'Datos de Contacto',
            },
        ),
        migrations.CreateModel(
            name='HomePageItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_portrait', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_image', models.ImageField(upload_to='')),
                ('portfolio_description', models.TextField()),
                ('portfolio_item_hosting', models.CharField(choices=[('EX', 'ExternalSite'), ('PD', 'PDF')], default='EX', max_length=2)),
                ('bio_file', models.FileField(blank=True, upload_to='')),
                ('external_site_url', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CasetllanoPortfolioItem',
            fields=[
                ('portfolioitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judith.portfolioitem')),
            ],
            options={
                'verbose_name': 'Portfolio (ES)',
                'verbose_name_plural': 'Portfolio (ES)',
            },
            bases=('judith.portfolioitem',),
        ),
        migrations.CreateModel(
            name='EnglishPortfolioItem',
            fields=[
                ('portfolioitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judith.portfolioitem')),
            ],
            options={
                'verbose_name': 'Portfolio (EN)',
                'verbose_name_plural': 'Portfolio (EN)',
            },
            bases=('judith.portfolioitem',),
        ),
    ]
