# Generated by Django 3.1 on 2020-08-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biocastellano',
            options={'verbose_name': 'Bio Castellano', 'verbose_name_plural': 'Bio Castellano'},
        ),
        migrations.AlterModelOptions(
            name='bioingles',
            options={'verbose_name': 'Bio Inglés', 'verbose_name_plural': 'Bio Inglés'},
        ),
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'verbose_name': 'Datos de Contacto', 'verbose_name_plural': 'Datos de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='homepageitems',
            options={'verbose_name': 'Homepage', 'verbose_name_plural': 'Homepage'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolio'},
        ),
        migrations.RemoveField(
            model_name='biocastellano',
            name='bio_file',
        ),
    ]
