# Generated by Django 3.1 on 2020-09-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='youtube_url',
            field=models.CharField(max_length=70),
        ),
    ]
