# Generated by Django 3.1 on 2020-09-06 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0002_auto_20200830_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasetllanoPortfolioItem',
            fields=[
                ('portfolioitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judith.portfolioitem')),
            ],
            options={
                'verbose_name': 'Portfolio (ES)',
                'verbose_name_plural': 'Portfolio (ES)',
            },
            bases=('judith.portfolioitem',),
        ),
        migrations.CreateModel(
            name='EnglishPortfolioItem',
            fields=[
                ('portfolioitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judith.portfolioitem')),
            ],
            options={
                'verbose_name': 'Portfolio (EN)',
                'verbose_name_plural': 'Portfolio (EN)',
            },
            bases=('judith.portfolioitem',),
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={},
        ),
    ]
