# Generated by Django 3.1 on 2020-08-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0002_auto_20200813_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
