# Generated by Django 3.1 on 2020-09-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0002_auto_20200911_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biocastellano',
            name='bio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bioingles',
            name='bio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='linked_in_url',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='telegram_url',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
