# Generated by Django 3.1 on 2020-09-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0003_auto_20200906_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='portfolio_item_hosting',
            field=models.CharField(choices=[('EX', 'ExternalSite'), ('PD', 'PDF')], default='EX', max_length=2),
        ),
    ]
