# Generated by Django 3.1 on 2020-08-13 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0003_auto_20200813_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='portfolio_dscription',
            new_name='portfolio_description',
        ),
    ]
