# Generated by Django 3.1 on 2020-09-06 20:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0004_auto_20200906_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biocastellano',
            name='bio_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='bioingles',
            name='bio_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
