# Generated by Django 3.1 on 2020-09-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0005_auto_20200921_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['-priority']},
        ),
    ]
