# Generated by Django 3.1 on 2020-08-13 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0005_auto_20200813_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='biocastellano',
            name='bio_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
