# Generated by Django 3.1 on 2020-08-13 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0006_biocastellano_bio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='external_site_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
