# Generated by Django 3.1 on 2020-09-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0006_auto_20200921_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='biocastellano',
            name='show_cv',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioingles',
            name='show_cv',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
