# Generated by Django 3.1 on 2020-08-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0007_portfolioitem_external_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='bio_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='external_site_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
