# Generated by Django 3.1 on 2020-09-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0007_auto_20200921_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biocastellano',
            name='show_cv',
            field=models.BooleanField(help_text='Destildar para esconder el link al CV en el bio'),
        ),
        migrations.AlterField(
            model_name='bioingles',
            name='show_cv',
            field=models.BooleanField(help_text='Destildar para esconder el link al CV en el bio'),
        ),
    ]
