# Generated by Django 3.1 on 2020-08-13 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0008_auto_20200813_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageitems',
            old_name='facebook_url',
            new_name='youtube_url',
        ),
    ]
