# Generated by Django 3.1 on 2020-08-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judith', '0009_auto_20200813_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='portfolio_item_hosting',
            field=models.CharField(choices=[('EX', 'ExternalSite'), ('PD', 'PDF')], default='PD', max_length=2),
        ),
    ]
